### ISSUE TITLE
[Discussion] Potential breaking changes for v6

### ISSUE THREAD

**Issue by chrisblossom** [davidtheclark/cosmiconfig#191]
Looks like #190 will be released soon and will require a major version bump.

Are there any potential changes to the API that should be considered before releasing `6.0.0`?

I personally would like to see this repository converted to typescript as it has a much larger community backing. I've recently made the switch and with some exceptions, I have found it a much more pleasant development experience. I'd be willing to put together an initial PR if that is something @davidtheclark @sudo-suhas @olsonpm is interested in. If not I completely understand...it isn't needed and somewhat "bikeshedding".

**Comment by davidtheclark** [comment]
Thanks for opening this, @chrisblossom. 

Re TypeScript: At this point, I wouldn't mind switching to TypeScript — it would be a good educational opportunity for me, since I don't have experience with it — especially if you're interested in putting in the legwork. I'm assuming it won't require significant refactoring of non-type code: if it does, I'd be more hesitant. If you want to start a PR towards that, go for it. If you're finding yourself making more than type-level changes though, it may be a good idea to pause and discuss those before you put in too much work.

**Comment by chrisblossom** [comment]
> I'm assuming it won't require significant refactoring of non-type code: if it does, I'd be more hesitant. ... If you're finding yourself making more than type-level changes though, it may be a good idea to pause and discuss those before you put in too much work.

Should be very straight forward with minimal changes necessary. I have a fair amount of experience what it takes to convert and update the build process. FYI, I don't think I'll have time to start on it until next week at the earliest.

I think the biggest change that you'll find is common js / module interop (which I think is currently an issue, just not very known). I think the best / most future proof solution is to remove default exports and use a named export instead. Relevant discussion: https://github.com/johnagan/clean-webpack-plugin/issues/114

```js
// es modules
import { cosmiconfig } from 'cosmiconfig';

// common js
const { cosmiconfig } = require('cosmiconfig');
```

**Comment by sudo-suhas** [comment]
While migrating to typescript(I too support this), we should try to use the [`--strict` compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html). However, I think we should minimise changes required for users to upgrade `cosmiconfig` unless there is a very good reason to do so.

**Comment by chrisblossom** [comment]
I put in PRs #192 #193 #194 #195 in preparation for typescript. The only one that is necessary is #194, the others are just things I noticed while updating the packages. Please close if they aren't wanted changes.

**Comment by chrisblossom** [comment]
Moved from https://github.com/davidtheclark/cosmiconfig/pull/197#issuecomment-504700070:

- [X] 1. Update build system to use babel and es modules. #198
- [x] 2. Direct minimal migration from typescript -> flow #201
- [x] 3. Add code quality tools such as [`@typescript-eslint/eslint-plugin`](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin) and fix any lint issues. (this was a big portion of the changed code) #202 
- [x] 4. Code PR bugs / issues found when updating types. #204
- [x] 5. Modernize code with async await. #205
- [ ] 6. Open discussion / PRs with API change ideas.
    - [ ] Replace `cosmiconfig.loaders` with named export `defaultLoaders` #208
    - [ ] Use `transformSync` option for sync transform #209
    - [ ] Only support `options.loaders` object format. 

I've opened some PRs to start discussions with some breaking changes I'm proposing. I'm not sure they are the best API possible, but wanted to open the PRs to get the process started.

**Comment by chrisblossom** [comment]
After #211 and #212 the only PR left for me to do before a new release is published is to fix/update the dependencies because of the issue described in #206.

**Comment by davidtheclark** [comment]
I just released v6 🎈
